### ISSUE TITLE
Unable to call validator on Linux command line

### ISSUE THREAD

**Issue by dancesWithCycles** [etalab/transport-validator#108]
Hi folks,
Thank you  very much for creating and maintaining this repository. Please accept my appreciation!

According to the [readme.md](https://github.com/etalab/transport-validator/blob/master/readme.md) I should invoke the following instructions on a Linux command line terminal to run the validator.

```
git clone https://github.com/etalab/transport-validator/
cd transport-validator
cargo run --release -- -i some_gtfs.zip
```

However, there is no file in this repository called ```cargo``` or I have not found it yet. Please point me in the right direction. Any hint is appreciated. Cheers!

**Comment by thbar** [comment]
Hi Stefan!

 `cargo` is a command normally provided by the Rust installation. You will have to install it as described here:

https://github.com/etalab/transport-validator#build-and-run

Hope it will fix your issue, let us know otherwise!
