### ISSUE TITLE
Additional warning: route_long_name in routes.txt is not specified

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-validator#120]
From https://github.com/etalab/transport-site/issues/2331

**Comment by Tristramg** [comment]
The spec says
> Either route_short_name or route_long_name must be specified, or potentially both if appropriate.

It doesn’t seem to hint that it is a general practice to have a `route_long_name`. For now, if both short and long name are missing, there is a warning.

**Comment by AntoineAugusti** [comment]
Sounds good. Asked to clarify this point https://github.com/etalab/transport-site/issues/2331#issuecomment-1110645735

**Comment by antoine-de** [comment]
Seen the related discussion, I think we can close this can't we @AntoineAugusti ?

**Comment by AntoineAugusti** [comment]
Yup, thanks!
