### ISSUE TITLE
Additional warning: route_color in routes.txt is not specified

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-validator#121]
From https://github.com/etalab/transport-site/issues/2331

**Comment by Tristramg** [comment]
>  Defaults to white (FFFFFF) when omitted or left empty

I would note consider this as a warning, not even an information. The specification is very explicit about this.

**Comment by AntoineAugusti** [comment]
This is important for route planners, to match "public facing material". Warning may not be appropriate but what about information or style?

**Comment by fchabouis** [comment]
closed by #126 , it won't be a warning, but the information will be accessible from the validation metadata.
