### ISSUE TITLE
Ajouter le nom du fichier contenant des erreurs/avertissements dans le rapport d'erreur 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/transport-validator#130]
Le rapport d'erreur du validateur GTFS ne mentionne le fichier qui contient des erreurs que quand il y a des erreurs irrécupérables comme ici : 
<img width="608" alt="image" src="https://user-images.githubusercontent.com/59559301/169820020-c6a2869c-52cc-412a-bf39-eae7984dc4f3.png">

ça pourrait être utile aux producteurs et réutilisateurs d'avoir cette précision pour les avertissements également. 
Dans cet exemple, on sait qu'il y a une URL invalide dans le fichier mais on ne sait pas dans quel fichier :
<img width="652" alt="image" src="https://user-images.githubusercontent.com/59559301/169820200-4d7a1ace-f6a7-4fec-a63b-7ff94486ca26.png">

Sans cette précision, le producteur pensait que c'était l'URL du GTFS même (GTFS moissonné) qui était invalide.

**Comment by fchabouis** [comment]
On ne va pas pouvoir donner l'information en général que le problème si situe à telle ligne de tel fichier. Il y a des erreurs qui n'ont pas de lignes particulières, par exemple un bus qui va trop vite entre 2 arrêts, cela fait intervenir tout une serie de ligne dans les fichiers (les coordonnées des stops, les horaires de passage, les jours de passage, etc). De plus on l'information des lignes quand on charge le fichier GTFS en mémoire et que quelque chose se passe mal. Mais une fois qu'il est chargé, et qu'on fait des checks dessus, on n'a plus accès aux numéros de ligne.

Par contre j'ai fait une PR pour rendre ce message d'erreur plus explicite et bien préciser qu'il s'agit du champ `agency_url`, dans le fichier agency.txt qui pose problème.

J'ai aussi fait en sorte qu'une url manquante ne déclenche pas 2 avertissements comme c'est le cas sur ta copie d'écran.
