### ISSUE TITLE
New warning if trips.shape_id references an unknown shapes.shape_id

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/transport-validator#135]
A warning is not raised at the moment. This creates confusion when trying to visualize shapes: a file exists but it's only possible to visualize stops.

https://github.com/etalab/transport-site/issues/2548

Sample GTFS with this problem.

[gtfs_stan.zip](https://github.com/etalab/transport-validator/files/9188408/gtfs_stan.zip)

**Comment by fchabouis** [comment]
closed by #148
