### ISSUE TITLE
Raise an error when files are in a subfolder

### ISSUE THREAD

**Issue by thbar** [etalab/transport-validator#160]
While doing a pass of data quality on https://transport.data.gouv.fr, I noticed a number of GTFS are considered valid despite containing a subfolder:

- https://github.com/etalab/transport-qualite-des-donnees/issues/7 
- https://github.com/etalab/transport-qualite-des-donnees/issues/8
- https://github.com/etalab/transport-qualite-des-donnees/issues/9
- https://github.com/etalab/transport-qualite-des-donnees/issues/10
- https://github.com/etalab/transport-qualite-des-donnees/issues/11
- https://github.com/etalab/transport-qualite-des-donnees/issues/12
- https://github.com/etalab/transport-qualite-des-donnees/issues/13
- https://github.com/etalab/transport-qualite-des-donnees/issues/14

I have opened this issue to discuss this at the spec level:
- https://github.com/google/transit/issues/377

Which raised a return so far:

> We get lots of support requests for exactly this topic in the OpenTripPlanner chat room.
> I would welcome the spec being more clear on this.

The crate used to read GTFS in the validator is smoothly handling that, but other tools may not etc, causing them trouble to ingest the data.

I would personally be happy to consider a file invalid on https://transport.data.gouv.fr if there is a subfolder, since it complicates the ingestion.

Given how the crate works, would it be complicated to return an error in that case (i.e. detect the fact that while data is valid, it wasn't stored at the root)?

To be discussed with the team (@fchabouis @AntoineAugusti), just raising the point with concrete data.

**Comment by antoine-de** [comment]
hum, it seems quite common for a GTFS to be nested, so not sure about this :thinking: 

Maybe we can just raise a warning for this though ? 

what are your thoughts on this @Tristramg ?

**Comment by Tristramg** [comment]
The spec might be more explicit here.

We used to be quite tolerant in order to start getting people to publish
data, but that era is now over. There seems to be a consensus towards
forbidding the sub-folders.

I suggest to wait until it get really into the spec. In the meantime, a
warning should be good

**Comment by thbar** [comment]
Quick update:

The spec is now more explicit:
- https://github.com/google/transit/pull/379

The MobilityData validator has implemented that as an ERROR:
- https://github.com/MobilityData/gtfs-validator/issues/1504

**Comment by AntoineAugusti** [comment]
Hi @antoine-de @Tristramg, would it be possible to add an error in the coming weeks with this rule?

**Comment by antoine-de** [comment]
yep, sure completly forgotten about this 👍
