### ISSUE TITLE
Move this repository to rust-transit?

### ISSUE THREAD

**Issue by antoine-de** [etalab/transport-validator#182]
A long time ago, we created a github organization, https://github.com/rust-transit, to host `gtfs-structures` hoping to host some transit tools made in rust.
I don't really remember why we did not put this project in it, I feel it would be more natural for it to be in the same place as `gtfs-structures`.

I'm thinking about this as @Tristramg will be giving a talk about rust-transit at [fosdem](https://fosdem.org/2024/).

I don't have high hopes on this, but maybe we can attract some contributors (like gtfs-structures that have 15 contributors).

What are you thoughts on this @thbar @AntoineAugusti ?

We would obviously need to rewrite the readme a bit to tell that it's founded by transport.data.gouv.fr and beta.gouv.fr

**Comment by AntoineAugusti** [comment]
Going to ask Benoit Queyron about this 👌

**Comment by AntoineAugusti** [comment]
I talked with @benoit-mint about this and he would like to keep this repository in a "gov-owned/labelled" organization for trustworthiness/branding purposes.

**Comment by antoine-de** [comment]
ok, fine for me :+1:
