### ISSUE TITLE
Route type extension

### ISSUE THREAD

**Issue by antoine-martin-ponts** [etalab/transport-validator#78]
Problème, ils utilisent une norme GTFS qu'on ne "valide" pas

https://transport.data.gouv.fr/resources/8354?issue_type=InvalidRouteType

https://transport.data.gouv.fr/datasets/reseau-de-transport-isibus

https://www.data.gouv.fr/fr/datasets/reseau-de-transport-isibus/

**Comment by antoine-de** [comment]
closed, the level have been lowered to `Information`
