### ISSUE TITLE
Validation d'un dossier de GTFS

### ISSUE THREAD

**Issue by chourmo** [etalab/transport-validator#84]
Les données de la Métropole Aix-Marseille_Provence sont comprennent plusieurs réseaux avec chacun sont propre dossier GTFS.

https://transport.data.gouv.fr/datasets/reseaux-de-transports-en-commun-de-la-metropole-daix-marseille-provence-et-des-bouches-du-rhone/

Serait il possible de valider globalement le dossier ou faut il leur demander de verser chaque GTFS à part ?

**Comment by antoine-de** [comment]
Bonjour,

Il faut effectivement verser chaque GTFS à part.

Ça me parait trop spécifique comme besoin pour qu’on permette cela, mais mon avis peut changer si d’autre personnes exprime le même besoin.

**Comment by fchabouis** [comment]
No other need expressed for GTFS folder validation, we close the issue for the moment.
