### ISSUE TITLE
Implement datatools validators

### ISSUE THREAD

**Issue by Tristramg** [etalab/transport-validator#9]
- [x] ReferencesTripValidator
- [x] TimeZoneValidator
- [ ] ServiceValidator
- [ ] MisplacedStopValidator
- [x] DuplicateStopsValidator
- [ ] NamesValidator
- [ ] TripValidator
- [ ] FeedValidator
- [x] SpeedTripValidator
- [ ] OverlappingTripValidator
- [ ] ReversedTripValidator
- [ ] PatternFinderValidator
- [ ] NewTripTimesValidator

**Comment by fchabouis** [comment]
@Tristramg tu peux m'expliquer ce que veut dire cette issue ?

**Comment by Tristramg** [comment]
À la base c’était une issue pour tracker l’avancement pour avoir au moins la même couverture de tests que datatools.

Je pense que certaines cases auraient du être cochées, mais que la liste s’est également allongée côté datatools.

**Comment by antoine-de** [comment]
I think we can close this, it was more to track the initial functionalities, but now we have real use cases
